// frontend/src/components/EmpresaSelect.tsx
import { useEffect, useState } from "react";
import { Select } from "antd";
import { createCrudApi } from "../api/crudFactory";

const cliforApi = createCrudApi("cliFor");

interface Props {
  value?: string;
  onChange: (value: string) => void;
  style?: React.CSSProperties;
}

/**
 * A maioria dos módulos de negócio (financeiro, contábil, patrimônio) é
 * escopada por cliente/empresa (campo `cliforid`, herdado do sistema
 * original). Este seletor é reutilizado em todas essas telas.
 */
export default function EmpresaSelect({ value, onChange, style }: Props) {
  const [options, setOptions] = useState<{ value: string; label: string }[]>([]);

  useEffect(() => {
    cliforApi.list().then((list: any[]) => {
      setOptions(list.map((c) => ({ value: c.id, label: c.nome ?? c.id })));
    });
  }, []);

  return (
    <Select
      placeholder="Selecione a empresa/cliente"
      style={{ width: 280, ...style }}
      value={value}
      onChange={onChange}
      options={options}
      showSearch
      optionFilterProp="label"
    />
  );
}

// frontend-vue/src/components/EmpresaSelect.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { createCrudApi } from "../api/crudFactory";

const props = defineProps<{ modelValue?: string; width?: string }>();
const emit = defineEmits<{ "update:modelValue": [value: string] }>();

const cliforApi = createCrudApi("cliFor");
const options = ref<{ value: string; label: string }[]>([]);

onMounted(async () => {
  const list = await cliforApi.list();
  options.value = list.map((c: any) => ({ value: c.id, label: c.nome ?? c.id }));
});

function onChange(value: string) {
  emit("update:modelValue", value);
}
</script>

<template>
  <a-select
    placeholder="Selecione a empresa/cliente"
    :style="{ width: props.width ?? '280px' }"
    :value="props.modelValue"
    :options="options"
    show-search
    option-filter-prop="label"
    @change="onChange"
  />
</template>
